### ISSUE TITLE
Blank toctree blocks cause error

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/doctools#17]
Line https://github.com/analogdevicesinc/doctools/blob/c6a1f67f799e0290cac9ae4d5a25bdc264450559/adi_doctools/__init__.py#L46

Not all these outputs are guaranteed to exist. For example if you have a block like:

```rst

.. toctree::
   :maxdepth: 2
   :caption: Contents:

```

This will fail

**Comment by gastmaier** [comment]
Fixed with https://github.com/analogdevicesinc/doctools/commit/fb6046f8dda100e63741c12a4236c28209e4a880  [v0.3.40](https://github.com/analogdevicesinc/doctools/releases/tag/v0.3.40) .
