### ISSUE TITLE
Two hdl-interfaces in the same rst file cannot share interface names

### ISSUE THREAD

**Issue by caosjr** [analogdevicesinc/doctools#3]
Currently, a single rst file cannot have two or more hdl-interfaces with conflicting names. It affects the collapsible content.

How to reproduce it:

```
.. hdl-interfaces::
    :path: library/jesd204/axi_jesd204_tx

.. hdl-interfaces::
    :path: library/jesd204/jesd204_tx
```

You will notice that only the first hdl-interface can show the "tx_cfg", "tx_ilas_config Enabled if LINK_MODE = 1.", "tx_event", "tx_status", "tx_ctrl Enabled if LINK_MODE = 1.", and "Ports" interfaces.

**Comment by gastmaier** [comment]
Solved in 7f7e73955b7d05aa8a3663889fe6876a26577a0c by appending the interface name to the sha1 method, which generated the hyperrefs.
