### ISSUE TITLE
TypedDict not in py7

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/doctools#8]
Need to bump version or drop the typehint for TypedDict. It got introduced in py3.8

https://github.com/analogdevicesinc/doctools/blob/58ed2bbd256ef3d0cd6beec11f8c0bdcdb090ebd/pyproject.toml#L36

**Comment by gastmaier** [comment]
Fixep in 8f73b0eebda70a10bc08b2c86306d475fb6cf715, bumped pkg to 0.3.31 to trigger release ([run](https://github.com/analogdevicesinc/doctools/actions/runs/8992055301))
